# Generated by Django 4.2 on 2023-05-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GptAPI',
            fields=[
                ('video_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='動画ID')),
                ('url', models.CharField(default='', max_length=200, verbose_name='URL')),
                ('title', models.CharField(default='', max_length=100, verbose_name='タイトル')),
                ('summary', models.JSONField(blank=True, default=[], null=True, verbose_name='要約')),
            ],
        ),
    ]
