# Generated by Django 4.2 on 2023-05-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeSummary',
            fields=[
                ('video_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('summary', models.JSONField(default=list)),
            ],
        ),
    ]
